### ISSUE TITLE
Update ALLOWED_HOSTS and add headers to readiness probe

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5514]
We should dial-in these host settings in our application:
https://github.com/CUAHSI/platform-recipes/blob/main/hydroshare/chart/templates/settings.yaml#L902
`ALLOWED_HOSTS = ["*"]`

We added for example
```
    ALLOWED_HOSTS = [
        '.hydroshare.org',  # Allow domain and subdomains
        '.hydroshare.org.',  # Also allow FQDN and subdomains
        'localhost',
    ]
```
But then pods failed their readiness probe.

We added a host header to our readiness Probe
https://github.com/CUAHSI/platform-recipes/blob/main/hydroshare/chart/templates/hydroshare.yaml#L65-L71
```yml
        readinessProbe:
          httpGet:
            path: /
            port: http
            httpHeaders:
              - name: Host
                value: hydroshare.org
```

That allows the pods to come up, but interestingly once they come up they cycle back through the [init-hydoshare](https://github.com/CUAHSI/platform-recipes/blob/4fe619901d62a536e3397b26b0f06a13943a54f3/hydroshare/chart/templates/hydroshare.yaml#L184-L209) and the application is never served
